<a href="https://colab.research.google.com/github/othniel77/datascience/blob/main/numpy_indexation_et_selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,11)
arr
# nous avons un stepsize par défaut de 1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Saisissons la valeur de l'index 8
arr[8]

8

In [ ]:
# extraire une tranche de valeur
arr[1:5]
# 5 non inclus

array([1, 2, 3, 4])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
# sans valeur de départ, on a 0 ou la première valeur par défaut
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
# Sans valeur d'arrivée, on a la valeur de fin par défaut
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
# Parlons du broadcasting
# réassigner une partie d'une liste avec une meme partie de meme forme et de meme taille
arr[0:5] = 100
# au début rien ne se pas
# nous remarquerons les valeurs de 0 à 5 ont subi une diffusion ou modification ou broadcasté de leur valeur à 100


In [ ]:
arr
# la valeur 100 a été diffusé ou broadcasté à travers ces valeurs

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)

In [ ]:
# je vais prendre une tranche de mon tableau ou slice , que je vais nommer slice
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
arr
# on trouvera que le tableau a été réinitialise avec des nombres de 0 à 10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# je peux aussi rédéfinir ma tranche, slice
slice_of_arr[:]=99
slice_of_arr
# nous trouverons que toute la tranche a été rédefini

array([99, 99, 99, 99, 99])

In [ ]:
# cette opération de broadcasting a affecté le tableau d'origine
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
# pour éviter le broadcasting, il fallait explicitement récopier le tableau
arr_copy = arr.copy()
arr_copy[:] = 100

In [ ]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
# on remarque que tableau arr n'a pas été changé
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
# Parlons de l'indexation des tableaux de dimension 2 avec des listes de point
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d.shape
# l'index 0 on a le nombre de lignes et l'index 1 le nombre de colonnes

(3, 3)

In [ ]:
# demande à quoi retourne l'index 0
arr_2d[0]
# elle nous retourne la toute première ligne

array([ 5, 10, 15])

In [ ]:
# pour saisir la dernière ligne
arr_2d[2]

array([35, 40, 45])

In [ ]:
# on peut aussi index à la ligne par un autre crochet
arr_2d[1][1]
# on veut avoir la deuxième ligne et le nombre du milieu

25

In [ ]:
# une autre façon de retourner 25 est
arr_2d[1,1]
# si on traduit, c'est de saisir l'élément à la ligne 2 et à la colonne 2

25

In [ ]:
# étendons cette notion sur la tranche
# selectionnons les deux premiers lignes
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [ ]:
# récupérons un sous tableau de notre tranche du tableau d'origine
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
# le type le plus courant, la solution conditionnelle
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# donnez moi des valeurs supérieurs à 4
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
# choisissons le tableau booléen
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
# demandons à nous retourner les valeurs pour lesquels on a true, avec les crochets
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
# faisons les 3 opérations de solutions conditionnelles dans une seule opération
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])