<a href="https://colab.research.google.com/github/othniel77/datascience/blob/main/op%C3%A9rations_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# additionnons notre tableau par 5
arr + 5
# tous nos elements sont additionnés à 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [5]:
# addition de deux tableaux, les 2 tableaux doivent avoir la meme forme ou shape
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# Pour ce qui est la division, numpy reserve un traitement particulier,surtout si on doit diviser par 0
# en effet, elle donne le résultat de la division avec un warning et pas un message d'erreur
arr / arr
# nous aurons dans notre résultat , un element nan (not a number)

<ipython-input-8-622eb5e34c51>:3: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [9]:
1/ arr
# cette opération nous donnera un element inf qui veut dire infini car c'est un entier sur 0

<ipython-input-9-242d0683eea9>:1: RuntimeWarning: divide by zero encountered in divide
  1/ arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [10]:
# calculons la racine carré de notre tableau
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [11]:
# utilisons les fonctions trigonométriques (sinus de chaque élement du tableau)
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [12]:
# Mesurons la logaritmique du tableau
np.log(arr)
# nous aurons un warning pour une division sur 0

<ipython-input-12-e7f48beddd8b>:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [13]:
# Nous avons travaillé sur un tableau de dimension 1
# travaillons sur un nouveau tableau de dimension 2

arr2d = np.arange(0,25).reshape(5,5)

In [14]:
arr2d.shape

(5, 5)

In [15]:
arr2d
# nous avons un tableau de dimension de 2 avec des lignes et des colonnes

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
# Calculons la somme du tableau
arr2d.sum()

300

In [17]:
# on peut aussi faire des somme le long des lignes et le long des colonnes
# on a (5,5) où le premier est l'index 0 qui correspond aux lignes et l'index 1 aux colonnes
# ainsi la somme le long des lignes pour chaque colonne vaut la somme sur l'index 0
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [18]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])