<a href="https://colab.research.google.com/github/othniel77/datascience/blob/main/Tableaux_ou_array_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# créons une liste python
my_list = [1,2,3]

In [3]:
# nous voulons savoir le type de notre liste qui est une list
type(my_list)

list

In [4]:
# pour transformer cette liste en tableau numpy, on fait
np.array(my_list)
# nous remarquerons une sortie différente mais qui ne change en rien notre liste d'origine ,qui est notre liste standard, notre liste Python

array([1, 2, 3])

In [6]:
# Assignons une variable pour sauvegarder notre tableau
my_arr = np.array(my_list)
my_arr
# nous obtiendrons le meme résultat que précédement et si on cherche le type, nous obtenons un type numpy


array([1, 2, 3])

In [7]:
# nous obtenons aussi ndarray pour n dimension
type(my_arr)

numpy.ndarray

In [8]:
# créons une liste de liste ou une liste imbriqué en Python
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix
# nous trouvons une liste standard Python dans lequel on trouve trois listes python qui contiennent chacune trois élements
# qu'est ce qui se produit quand on passe la liste imbriqué dans la fonction numpy

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)
# nous notons que numpy sait déja que c'est une tableau de dimension 2, en effet trois lignes pour trois colonnes, cela va etre une des idées clés de numpy
# cette idée clé est de manipuler les données et appliquer des fonctions sur des dataset bidimensionnels

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# regardons certains fonctions numpy, une des plus utiles np.arange équivalent de la fonction range de python avec des parametre start,step,stop
np.arange(0,10)
# cela démarre à 0 et va à 10 non inclus soit de 0 à 9



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# ajouter la valeur step , ici 2 càd qui démarre à la valeur 0 et qui va à une valeur + 2
np.arange(0,10,2)
# la liste s'arrete à 8 car la fonction n'inclut pas 10

array([0, 2, 4, 6, 8])

In [12]:
# un autre exemple
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [13]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [14]:
# il est souvent besoin de créer de gros dataset de 0 et 1, lorsqu'on veut créer des dataset réel.on utilise np.zerosn qui demande shape(vecteur de 0 shape)
np.zeros(5)
# nous obtenons un vecteur de 5 zéros car le shape est 5.les 0 sont des nombres décimaux mais numpy retient les nombre avant la virgule

array([0., 0., 0., 0., 0.])

In [15]:
# faisons un tuple de shape
np.zeros((5,5))
# le premier nombre est le nombre de lignes et le deuxime le nombre de colonnes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
# changeons pour avoir 2 lignes , pour avoir un tuple de 5
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
# nous avons une autre fonction pour les 1
np.ones((4,4))
# 4 lignes et 4 colonnes

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
# un tuple avec autant de 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
# une autre fonction est linspace avec le point de départ start et d'arrivée stop, et le nombre qu'on veut. ici stop est inclus car endpoint = true par défaut
np.linspace(0,10,3)
# ici je demande à nympy de me donner trois nombre linéairement et régulièremet espacé entre 0 et 10.

array([ 0.,  5., 10.])

In [21]:
# on peut étendre cette espace de 3  à 11 et avoir 11 membres linérairement espacé
np.linspace(0,10,11)
# on peut avoir des valeurs virgules si on veut d'autre nombre entre start et stop

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [23]:
len(np.linspace(0,10,11))

11

In [24]:
# regardons une autre fonction eye, qui crée une matrice identité et on met un seul nombre car une matrice identité est une matrice carrée
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
# comment nous pouvons créer des distributions des données aléatoires
# il y a une tonne de fonctions (des lois statistiques) pour les données aléatoires
# la première fonction que nous allons apprendre est la fonction rand
np.random.rand(1)
# échantillon aléatoire avec une distribution uniforme avec une distribution de (0,1)
# on va avoir des nombres autour de 0 et 1

array([0.21325618])

In [27]:
# on peut aussi créer des tuples avec des lignes et des colonnes
np.random.rand(5,6)
# ici 5 lignes et 6 colonnes

array([[0.49657039, 0.682247  , 0.32156092, 0.59402699, 0.18978357,
        0.92987064],
       [0.22125731, 0.3033857 , 0.59841693, 0.17354012, 0.94609536,
        0.6179196 ],
       [0.63083762, 0.60843546, 0.98375169, 0.90563824, 0.70120947,
        0.01658504],
       [0.8639683 , 0.76032858, 0.52150446, 0.16725983, 0.64317561,
        0.80856149],
       [0.66206228, 0.58274582, 0.74919174, 0.31461711, 0.12248884,
        0.18900788]])

In [28]:
# Dans le monde physique qui nous entoure beaucoup utilise de la distribution normale
np.random.randn(10)
# on a randn pour avoir une distribution normale standard avec une moyenne de 0 et une variance de 1
# puisque la moyenne est 0, on peut avoir des nombres négatives
# très similaires avec la fonction rand

array([-0.12424828,  0.22340079, -1.38829832,  0.04033143, -0.85139328,
        0.2441    , -0.30163861, -0.5644225 ,  0.68220845,  0.26160616])

In [29]:
np.random.randn(2,3)

array([[-1.00431132,  1.50835179,  0.52137687],
       [-0.47716016,  0.41484207, -0.69057075]])

In [30]:
# une autre fonction est randint qui retourne les entiers aléatoires avec des seuils (inféreiurs et supérieurs)
# ceci retourne des entiers aléatoires compris entre ces deux seuils uniformement, ces entiers ont la meme probabilité de sortir
# on a un troisième argument  qui est size, et cela retourne size entier aléatoire
np.random.randint(0,101,5)
# ici nous aurons 5 entiers aléatoires

array([73, 17, 63,  0, 50])

In [31]:
# on peut avoir des tableaux avec des tuples avec lignes et des colonnes
np.random.randint(0,101,(4,5))


array([[81, 69, 53, 80, 27],
       [15, 39, 38,  7, 68],
       [11, 19, 42, 55, 96],
       [58, 45, 15, 40, 38]])

In [32]:
# avoir l'age de dix personnes aléatoires
np.random.randint(0,101,10)

array([27, 86, 22, 77, 25, 62,  6, 67, 72,  4])

In [33]:
# on peut fixer le nombre seed , ici on mettra 42 qui fait réference à l'explorateur Douglas
# et puis il faut determiner dans la meme cellule , la fonction rand.
# il faut impérativement le faire sur la meme cellule sinon, elle va pas s'éxécuter
np.random.seed(42)
np.random.rand(4)
# 4 nombres aléatoires comprise entre 0 et 1
# le nombre de seed n'est pas important , on peut mettre 1, 101, 4 mais ce qui est important ce que les deux lignes vont les memes nombres aléatoires à chaque fois.

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [34]:
# nous allons voir la fonction reshape qui permet de reformater un tableau numpy
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
# nous voulons les memes nombres mais dans un schéma différents
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
# certains appels de méthodes utiles
ranarr = np.random.randint(0,101,10)
ranarr
# cherchons la valeur max de ce tableau et la valeur min du tableau

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [37]:
ranarr.max()

99

In [38]:
ranarr.min()

2

In [39]:
#l'emplacement des index pour la valeur max et la valeur min avec argmax et argmin
ranarr.argmax()

5

In [40]:
ranarr.argmin()

7

In [41]:
# on peut aussi appeler le type de donnée avec dtype sans parenthèse
ranarr.dtype
# cela donne aussi le nombre de bytes 32 ou 64

dtype('int64')

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
# on va utiliser l'attribut shape (car sans paranthèse) différent d'une méthode reshape()
arr.shape

(25,)

In [45]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
# on peut vérifier le résultat de la forme actuelle
arr.shape

(5, 5)

In [47]:
# le resultat de arr.shape est tres différent de arr.reshape(1,25) et arr.reshape(25,1)
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [48]:
# ici on aura une double crochet, ici on a un vecteur à deux dimensions alors que le premier est un vecteur à un seul dimension.
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])